# This is an example .yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64

dockers:
- image_templates:
  - ghcr.io/juusujanar/ttn-exporter:{{ .Version }}-amd64
  - janarj/ttn-exporter:{{ .Version }}-amd64
  use: buildx
  dockerfile: Dockerfile
  goos: linux
  goarch: amd64
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
- image_templates:
  - ghcr.io/juusujanar/ttn-exporter:{{ .Version }}-arm64
  - janarj/ttn-exporter:{{ .Version }}-arm64
  use: buildx
  dockerfile: Dockerfile
  goos: linux
  goarch: arm64
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
- image_templates:
  - ghcr.io/juusujanar/ttn-exporter:{{ .Version }}-armv7
  - janarj/ttn-exporter:{{ .Version }}-armv7
  use: buildx
  dockerfile: Dockerfile
  goos: linux
  goarch: arm
  goarm: 7
  build_flag_templates:
  - --platform=linux/arm/v7
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}

docker_manifests:
  - name_template: ghcr.io/juusujanar/ttn-exporter:{{ .Version }}
    image_templates:
      - ghcr.io/juusujanar/ttn-exporter:{{ .Version }}-amd64
      - ghcr.io/juusujanar/ttn-exporter:{{ .Version }}-arm64
      - ghcr.io/juusujanar/ttn-exporter:{{ .Version }}-armv7
  - name_template: ghcr.io/juusujanar/ttn-exporter:latest
    image_templates:
      - ghcr.io/juusujanar/ttn-exporter:{{ .Version }}-amd64
      - ghcr.io/juusujanar/ttn-exporter:{{ .Version }}-arm64
      - ghcr.io/juusujanar/ttn-exporter:{{ .Version }}-armv7
  - name_template: janarj/ttn-exporter:{{ .Version }}
    image_templates:
      - janarj/ttn-exporter:{{ .Version }}-amd64
      - janarj/ttn-exporter:{{ .Version }}-arm64
      - janarj/ttn-exporter:{{ .Version }}-armv7
  - name_template: janarj/ttn-exporter:latest
    image_templates:
      - janarj/ttn-exporter:{{ .Version }}-amd64
      - janarj/ttn-exporter:{{ .Version }}-arm64
      - janarj/ttn-exporter:{{ .Version }}-armv7

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
