version: 2

project_name: ttn-exporter
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"

dockers_v2:
  - images:
      - "ghcr.io/juusujanar/{{ .ProjectName }}"
      - "janarj/{{ .ProjectName }}"
    tags:
      - "v{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    dockerfile: Dockerfile
    labels:
      "org.opencontainers.image.description": "Things Stack Prometheus exporter"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
