{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ttn-exporter.fullname" . }}
  labels:
    {{- include "ttn-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ttn-exporter.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        - port: http
          protocol: TCP
      {{- if .Values.networkPolicy.from }}
      from:
        {{- toYaml .Values.networkPolicy.from | nindent 8 }}
      {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - {}
  {{- end }}
{{- end }}
